// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:ecounity/src/objects/badge_status_item.dart';
import 'package:ecounity/src/objects/ecounity_badge.dart';
import 'package:ecounity/src/objects/pathway_stage.dart';
import 'package:ecounity/src/objects/pathway_status.dart';
import 'package:ecounity/src/objects/pathway_status_item.dart';
import 'package:ecounity/src/objects/pathway_type.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BadgeStatusItemAdapter());
    registerAdapter(EcoUnityBadgeAdapter());
    registerAdapter(PathwayStageAdapter());
    registerAdapter(PathwayStatusAdapter());
    registerAdapter(PathwayStatusItemAdapter());
    registerAdapter(PathwayTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BadgeStatusItemAdapter());
    registerAdapter(EcoUnityBadgeAdapter());
    registerAdapter(PathwayStageAdapter());
    registerAdapter(PathwayStatusAdapter());
    registerAdapter(PathwayStatusItemAdapter());
    registerAdapter(PathwayTypeAdapter());
  }
}
